[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/admin/printer_alpha_data/comms/klippy.sock

[authorization]
trusted_clients:
  127.0.0.0/8
  192.168.1.0/24
  192.168.3.0/24
cors_domains:
  http://192.168.1.224
  *.local
  *.home
  *://localhost:*
  http://my.mainsail.xyz
  http://app.fluidd.xyz
force_logins: False

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
path: /home/admin/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/admin/mainsail-config
primary_branch: master
type: git_repo

[update_manager klipper-backup]
type: git_repo
path: /home/admin/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main

[include moonraker-obico-update.cfg]
